# xsim.tcl  (Vivado Tcl에서 배치/GUI 공통 사용)
# Usage:
#   vivado -mode tcl -nolog -nojournal -notrace \
#     -source xsim.tcl -tclargs "<rtl_globs>" "<tb_file>" <top> [--gui]

# --- 인자 파싱 ---
set args $::argv
if {[llength $args] < 3} {
  puts "USAGE: -tclargs \"<rtl_globs>\" \"<tb_file>\" <top> [--gui]"
  exit 1
}
set RTL_GLOBS [lindex $args 0]
set TB_FILE   [lindex $args 1]
set TOP       [lindex $args 2]
set GUI       [expr {[lsearch -exact $args "--gui"] >= 0}]

# --- 글롭 확장 ---
set RTL_LIST {}
foreach g [split $RTL_GLOBS " "] {
  if {$g eq ""} { continue }
  foreach f [glob -nocomplain $g] {
    lappend RTL_LIST [file normalize $f]
  }
}
if {[llength $RTL_LIST] == 0} {
  puts "No RTL matched: $RTL_GLOBS"
  exit 2
}
set TB_FILE [file normalize $TB_FILE]

# --- 스냅샷 이름 ---
set snap "${TOP}_sim"

# --- xvlog ---
set cmd1 [list xvlog]
eval lappend cmd1 $RTL_LIST $TB_FILE
puts [join $cmd1 " "]
if {[catch {exec {*}$cmd1} err]} {
  puts "xvlog failed: $err"
  exit 3
}

# --- xelab ---
set cmd2 [list xelab $TOP -s $snap --debug typical]
puts [join $cmd2 " "]
if {[catch {exec {*}$cmd2} err]} {
  puts "xelab failed: $err"
  exit 4
}

# --- VCD 덤프용 스크립트 경로 ---
set runScript [file normalize "xsim_run_vcd.tcl"]

# 스크립트가 없으면 기본 내용으로 자동 생성
if {![file exists $runScript]} {
  set fh [open $runScript "w"]
  puts $fh {# xsim_run_vcd.tcl - auto generated by xsim.tcl
# 1) VCD 설정
open_vcd sim.vcd        ;# VCD 파일 이름
log_vcd *               ;# 모든 신호 VCD에 로깅

# 2) GUI(wdb) 파형 로깅
log_wave -recursive *   ;# GUI에서 볼 모든 신호 기록

# 3) 시뮬레이션 실행 (필요하면 시간 조절 가능)
run 1 us

# 4) VCD 닫기
close_vcd

# 5) 종료 동작 (GUI/배치 구분)
if {[info exists ::env(XSIM_GUI)] && $::env(XSIM_GUI) eq "1"} {
    # GUI 모드: 창 유지
    return
} else {
    # 배치 모드: 시뮬레이터 종료
    quit
}}
  close $fh
}

# --- xsim 실행 ---
if {$GUI} {
  # GUI 모드: 환경변수로 GUI 플래그 전달
  set ::env(XSIM_GUI) 1
  set cmd3 [list xsim $snap -gui -tclbatch $runScript]
} else {
  # 배치 모드
  set ::env(XSIM_GUI) 0
  set cmd3 [list xsim $snap -tclbatch $runScript]
}

puts [join $cmd3 " "]
if {[catch {exec {*}$cmd3} err]} {
  puts "xsim failed: $err"
  exit 5
}
